const coursesListObject = {
  sei: {
    title: 'SOFTWARE ENGINEERING IMMERSIVE',
    price: 'N400,000',
    duration: '12 Weeks',
    courses: [
      {
        title: 'Overview',
        topics: [
          'A brief tour into the course',
        ],
      },
      {
        title: 'The Power of Learning Ruby and JavaScript',
        topics: [
          'Lessons on the pros of learning Ruby and Javascript',
        ],
      },
      {
        title: 'Curriculum Overview',
        topics: [
          'Full Stack Web Development',
          'Technical Concentrations',
          'Product Management',
          'Computer Science',
        ],
      },
      {
        title: 'The Full Stack Journey: An In-Depth Look',
        topics: [
          'A brief tour into the world of being a Full Stack Developer',
        ],
      },
      {
        title: 'What Makes a Software Engineer?',
        topics: [
          'The pros and cons of being an Engineer',
        ],
      },
    ],
  },
  frontendCourses: {
    title: 'FRONTEND DEVELOPER',
    price: 'N300,000',
    duration: '8 Weeks',
    courses: [
      {
        title: 'UI & UX',
        topics: [
          'What is UI & UX?',
          'What is the difference between UI & UX?',
          'Who is a user experience designer?',
          'Learning UI & UX',
          'What is the UX design process?',
          'Steps to becoming a UI & UX designer.',
        ],
      },
      {
        title: 'Javasript',
        topics: [
          'Introduction to JavaScript',
          'What is Java scripting language?',
          'What are the main features of JavaScript',
          'Where is JavaScript used?',
          'What is the purpose of JavaScript?',
        ],
      },
      {
        title: 'HTML',
        topics: [
          'What is HTML and how it is used',
          'HTML Basics',
          'HTML tags and Text Emphasis',
          'HTML Lists and Images',
          'HTML Links and Internal Links',
          'HTML Tables and Comments',
        ],
      },
      {
        title: 'CSS',
        topics: [
          'What is CSS?',
          'What is CSS used for?',
          'What is webfonts?',
          'CSS style attributes, namespaces, stylesheets using xml documents',
          'Document object model.',
          'CSS template Layout, Snapshot, Scrollsnap, Containment, Grid Layout',
          'CSS Encoding',
          'CSS Backgrounds and borders, Basic User interfaces, shapes, syntax, fragmentation, Cascading and Inheritance and Fragmentation Module',
        ],
      },
    ],
  },
  backendCourses: {
    title: 'BACKEND DEVELOPER',
    price: 'N300,000',
    duration: '8 Weeks',
    courses: [
      {
        title: 'PHP',
        topics: [
          'What is PHP?',
          'What language is used in PHP?',
          'Why PHP language is used',
          'What is the meaning of PHP in computer language?',
          'What can PHP do?',
          'What does a PHP developer do?',
          'PHP programming language with object-oriented-programming support',
        ],
      },
      {
        title: 'Java',
        topics: [
          'What type of programming language is Java',
          'What is the use of Java programming language?',
          'Who invented the Java programming language and why?',
          'The Java Language',
          'The Java Compiler',
          'The JVM',
          'The garbage collector',
          'Object oriented programming on the Java platform.',
        ],
      },
      {
        title: 'Python',
        topics: [
          'Is python a programming or scripting language?',
          'What is python used for?',
          'Python for beginners.',
          'Important things python programmers should know',
        ],
      },
      {
        title: 'Ruby',
        topics: [
          'What is Ruby?',
          'What is Ruby code used for?',
          'What kind of language is Ruby?',
          'What are Ruby and Python used for?',
          'Why learn Ruby?',
          'What can Ruby do?',
          'Ruby vs. Ruby on rails',
        ],
      },
      {
        title: 'Ruby on Rails',
        topics: [
          'Introduction to Ruby on rails',
          'What is Ruby on rails?',
          'What is it used for?',
          'Ruby on rails vs. PHP',
          'Examples of Ruby on Rails',
          'Ruby on rails jobs',
        ],
      },
      {
        title: '.NET',
        topics: [
          'Pronounced .NET',
          'What is the .NET programming language?',
          'What is the .NET technology?',
          'What is the difference between .NET and C#?',
          'What is the .NET platform?',
          '.NET programming language',
          'All you need to know about the .NET framework',
        ],
      },
    ],
  },
  mobileAppsIos: {
    title: 'MOBILE APPLICATION IOS',
    price: 'N300,000',
    duration: '6 Weeks',
    courses: [
      {
        title: 'Swift',
        topics: [
          'A look into the Swift concept',
        ],
      },
      {
        title: 'Object Oriented Programming',
        topics: [
          'What is OOP?',
        ],
      },
      {
        title: 'Interface Design and Implementation',
        topics: [
          'How to design IOS User Interface',
        ],
      },
      {
        title: 'Data Stores/Core Data',
        topics: [
          'Storage in IOS?',
        ],
      },
      {
        title: 'Advanced Views',
        topics: [
          'How to build Advanced Views',
        ],
      },
      {
        title: 'APIs/Multi­-Threading',
        topics: [
          'MultiThreading in IOS',
        ],
      },
      {
        title: 'Projects',
        topics: [
          'Test your skills with the Final Project',
        ],
      },
    ],
  },
  mobileAppsAndroid: {
    title: 'MOBILE APPLICATION ANDROID',
    price: 'N300,000',
    duration: '6 Weeks',
    courses: [
      {
        title: 'Fundamentals',
        topics: [
          'Software Engineering',
          'SQL Queries',
          'Basics of Designing TOPSTechnologies-Androidtraining program',
        ],
      },
      {
        title: 'Learning the Language (Java)',
        topics: [
          'Introduction to Java',
          'Bytecodes and Java Virtual Machine',
          'Applications and Applets',
          'Java Development Kit',
          'Data types',
          'Loops',
          'Conditionals',
          'Operators',
          'Arrays TOPSTechnologies-Androidtraining program',
          'Classes and Objects',
          'Encapsulation',
          'Constructors',
          'Inheritance',
          'Method Overriding',
          'Polymorphism',
          'Abstract Methods and classes ',
          'Interface',
          'Packaging',
          'Exceptional Handling TOPSTechnologies-Androidtraining program',
          'Multitasking',
          'Multithreading',
          'Synchronization',
          'Java I/O',
          'XML Parse using DOM',
          'SAX Parser',
          'Abstract Windows Toolkit',
          'Component',
          'Java Swing TOPSTechnologies-Androidtraining program',
        ],
      },
      {
        title: 'Android OS',
        topics: [
          'Introduction to Java And Android',
          'Introducing Development Framework',
          'Dalvik Virtual Machine – DVM',
          'Developing with Eclipse',
          'Android Virtual Device and SDK Manager',
          'Android Architecture and OOPS',
          'Android Development Tools',
          'Android Asset Packaging Tool (AAPT)',
          'Android Debug Bridge',
          'Types of Android Applications',
          'Android Architecture and OOPS',
          'Activity Lifecycle',
          'Activity classes',
          'Introduction to Application Manifest',
          'Installing Android',
          'Component Lifecycle TOPSTechnologies-Androidtraining program',
        ],
      },
      {
        title: 'Building Mobile Applications with Android',
        topics: [
          'Android layouts',
          'Android UI and Advance Java',
          'Android GUI Architecture',
          'Layouts',
          'Android Widget Toolbox',
          'WebView',
          'GridView',
          'Understanding Android Menus',
          'Intents and Processes',
          'Graphics Animation and Multimedia',
          'Bitmaps TOPSTechnologies-Androidtraining program',
          'Introduction to Audio on Android',
          'Introduction to Video',
          'Android Persistence',
          'Android Preferences',
          'Using File system ',
          'Accessing SD cards',
          'Location and maps',
          'Using GEOCoder',
          'Creating and Using Overlays',
          'Projections',
          'Using Wake Locks',
          'Android Text To Speech',
          'Interprocess Communication',
          'Paranoid Android',
          'Internet Services TOPSTechnologies-Androidtraining program',
          'Broadcast receivers',
          'Using Camera',
          'Sensor Manager',
          'Bluetooth',
          'Network',
          'Wi-Fi',
          'AIDL and IPC',
          'XML Parsing',
          'Dom Parsing',
          'SAX Parsing',
          'JSON Parsing',
          'SQLite Databases',
          'Services and Content Providers',
          'Introduction to Android NDK TOPSTechnologies-Androidtraining program',
        ],
      },
      {
        title: 'Database Connectivity',
        topics: [
          'SQLite Data Types',
          'Cursors and Content Values',
          'SQlite Open Helper',
          'Adding, Updating and Deleting Content TOPSTechnologies-Androidtraining program',
        ],
      },
      {
        title: 'Applicability to Industrial Projects',
        topics: [
          'Project Scope',
          'Database Dictionary',
          'Flow Chart',
          'High Level Requirements',
          'sing Bluetooth and NFC in Android device',
          'Localization in Android',
          'Configuration changes',
          'Security and permissions',
          'Web Services Integration',
          'Deployment TOPSTechnologies-Androidtraining program',
        ],
      },
    ],
  },
  bas: {
    title: 'BUSINESS APPLICATION SOFTWARE',
    price: 'N150,000',
    duration: '3 Days',
    courses: [
      {
        title: 'Adobe Premiere Pro',
        topics: [
          'What is Adobe Premiere Pro?',
          'Is Adobe Premiere Pro free?',
          'What is Adobe Prelude?',
          'What is Adobe after effects used for?',
          'Adobe Premiere Pro Overview',
          'An id-depth look at the Adobe Premiere Pro Editing Tools',
        ],
      },
      {
        title: 'Power presentation',
        topics: [
          'Introduction to PowerPoint',
          'How to make a PowerPoint presentation?',
          'Basic tasks for Creating a PowerPoint presentation.',
          'Be a Power user!!',
        ],
      },
      {
        title: 'Microsoft Excel- Advanced Analysis',
        topics: [
          'Introduction to Data Analysis using Microsoft Excel',
          'Integrated Excel for Advanced Analysis and Reporting',
          'Mastering Data Analysis in Excel',
          'Learn Data Analysis Regression',
        ],
      },
      {
        title: 'Microsoft Visio',
        topics: [
          'What is Microsoft Visio ?',
          'What does it do and how does it work?',
          'Is Microsoft Visio part of Microsoft office package or office 365?',
          'Create your own Flowcharts and Diagrams',
        ],
      },
      {
        title: 'SAP – System Applications Products',
        topics: [
          'What is SAP?',
          'What is it used for and how does it work?',
          'What is the purpose of a SAP certification?',
          'An In-depth knowledge of SAP.',
        ],
      },
      {
        title: 'Peach Tree',
        topics: [
          'What id Peach Tree?',
          'Uses of Peach Tree',
          'Is Peach Tree and Sage 50 the same?',
          'What is Sage 50?',
          'Advantages of using Peach Tree Accounting Software',
          'Peach Tree vs. QuickBooks',
        ],
      },
      {
        title: 'SAGE Enterprise Resource Planning',
        topics: [
          'Sage ERP solutions',
          'Sage ERP X3',
          'Sage 100 ERP',
          'Sage 300 ERP',
          'Sage 500 ERP',
          'What is Sage 50?',
          'Sage ERP custom Development',
          'Choosing an ERP system',
        ],
      },
      {
        title: 'Corel Draw',
        topics: [
          'What is Corel draw?',
          'Uses and feature',
          'Basic tips on Corel draw',
          'Next definition, terms and tools associated with Corel draw.',
        ],
      },
    ],
  },
  shortCourses: {
    title: 'SHORT COURSES',
    price: 'N200,000',
    duration: '4 Weeks',
    courses: [
      {
        title: 'Python',
        topics: [
          'Is python a programming or scripting language?',
          'What is python used for?',
          'Python for beginners.',
          'Important things python programmers should know',
        ],
      },
      {
        title: 'Ruby',
        topics: [
          'What is Ruby?',
          'What is Ruby code used for?',
          'What kind of language is Ruby?',
          'What are Ruby and Python used for?',
          'Why learn Ruby?',
          'What can Ruby do?',
          'Ruby vs. Ruby on rails',
        ],
      },
      {
        title: 'Ruby on Rails',
        topics: [
          'Introduction to Ruby on rails',
          'What is Ruby on rails?',
          'What is it used for?',
          'Ruby on rails vs. PHP',
          'Examples of Ruby on Rails',
          'Ruby on rails jobs',
        ],
      },
      {
        title: 'Java',
        topics: [
          'What type of programming language is Java',
          'What is the use of Java programming language?',
          'Who invented the Java programming language and why?',
          'The Java Language',
          'The Java Compiler',
          'The JVM',
          'The garbage collector',
          'Object oriented programming on the Java platform.',
        ],
      },
      {
        title: 'React',
        topics: [
          'What is React?',
          'What is JSX?',
          'What is the Redux?',
          'What is Redux and react?',
          'What is React.js?',
          'React.js for the visual learner',
          'Should I use React?',
        ],
      },
    ],
  },
};

export default coursesListObject;
